plugins {
	id 'eclipse'
	id 'idea'
	id 'net.minecraftforge.gradle' version '[6.0,6.2)'
	id 'org.spongepowered.mixin' version '0.7.+'
	id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = '0.0.2'
group = 'bonetorch'

base {
	archivesName = 'SBM-BoneTorch-1.20.1'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

minecraft {
	mappings channel: 'parchment', version: '2023.09.03-1.20.1'
	copyIdeResources = true
	
    runs {
        client {
            workingDirectory project.file('run/client')
            property 'forge.logging.console.level', 'debug'

            mods {
                bonetorch {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run/server')
            property 'forge.logging.console.level', 'debug'
			args '-nogui'

            mods {
                bonetorch {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        url "https://www.cursemaven.com"
    }
}

dependencies {
	minecraft 'net.minecraftforge:forge:1.20.1-47.1.3'

    //implementation fg.deobf("curse.maven:silent-lib-242998:3543045") //torch bandolier dependency
    //implementation fg.deobf("curse.maven:torch-bandolier-299337:3550328")
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "SBM-BoneTorch",
                    "Specification-Vendor": "Built Broken Modding",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "SBM-BoneTorch",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor" :"Built Broken Modding"],)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}